# Language standards {#languagestandards}

When developing research software that you would like others to use, it is good to keep in mind that the "latest greatest" features of any one language are often not in wide use.  For example, at the time of this writing, Python 3.8 is in beta and Python 3.7 is installed in the "latest" installer for the Anaconda/Miniconda systems.  However, several Python libraries with back-ends written in `C` or `C++` may not have been updated to a change to the Python `C` API that is not backwards-compatible, thus limiting your ability to use 3.7.  Further, many Linux and OS X installations are likely to have even earlier versions installed by default. In fact, 2.7 will be the default on most systems, with Python 3 requiring some extra work to install.

The same goes for `C` and even more so for `C++`.  The current `C` standard is `C11` (that's 2011), but most folks are probably still programming in `C99` (1999), and Microsoft's compilers don't fully support either of those standards.  With `C++`, the `C++11` standard brought in an era of "modern" `C++` syntax [@Meyers2014-se], incorporating a slew of features from the [boost](http://www.boost.org) libraries into the main language.  Currently, the `C++20` standard is now largely agreed upon, but fully-implemented essentially nowhere that I am aware of.  For all practical purposes, `C++14` is the only standard that one can reasonably expect to be decently supported on up-to-date systems.

Similar logic can, and should, be applied to Python and `R` libraries.  Using a feature only found in the latest [dplyr](http://dplyr.tidyverse.org) commit to the master branch is a good way to frustrate users.

I generally use `conda` as a sanity check on what is a reasonable dependency.  The latest builds use `GCC 7.3` for Linux and a reasonably new `clang` on OS X.  See [here](https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/) for details.  Both have full support for `C++14` and `C99`. The `conda-forge` and `r` channels have a recent version of `R` (currently 3.5.1) and current versions of popular tool chains like the [tidyverse](http://www.tidyverse.org) [@Wickham2017-kh].  Anaconda tends to have current packages for newer languages like [julia](http://www.julialang) and [rust](http://www.rust-lang.org).

If you insist of using cutting-edge versions of various tools, you should probably be prepared to create and maintain [Docker](http://www.docker.com) and/or [Singularity](https://singularity.lbl.gov/) images containing your tool chain and compiled products.

For the record, I have zero patience/sympathy for cluster systems hanging on to ancient versions of `GCC` due to ancient versions of `CentOS`.  Don't "at" me.
